texts = {
    'French' : {
        'language' : ['Français', 'Anglais', 'Allemand'],
        'self_language' : "Français",
        'language_indication' : 'Choisissez une langue',
        'quit' : "Quitter",
        'open_file' : "Charger un nouveau fichier",
        'select_file' : "Sélectionner un fichier",
        'save_file' : "Sauvegarder un fichier",
        'go_back' : "Retourner au menu",
        'merge_complete_title' : "Succès de l'enregistrement",
        'merge_complete_message' : "Le nouveau PDF a bien été enregistré !",
        'split_complete_title' : "Succès de l'enregistrement",
        'split_complete_message' : "Le nouveau PDF a bien été enregistré !",
        'missing_start_page_title' : "Page de début incorrecte",
        'missing_start_page_message' : "Veuillez indiquez le numéro de la page à partir de laquelle vous souhaitez commencez à extraire les pages du fichier.\nLe nombre saisi doit être entier (pas de virgule) et positif.",
        'missing_stop_page_title' : "Page de fin incorrecte",
        'missing_stop_page_message' : "Veuillez indiquez le numéro de la page à laquelle vous souhaitez arrêter d'extraire les pages du fichier.\nLe nombre saisi doit être entier (pas de virgule), positif et il doit être supérieur au nombre saisi pour la page de début.",
        'start_stop_too_big_title' : "Le PDF a moins de pages que vous ne pensez ;)",
        'start_stop_too_big_message' : ["Les nombres que vous avez saisis pour les pages de début et/ou de fin ne correspondent pas à la taille du fichier.\nVeuillez prendre en compte que le fichier ne contient que ", " page(s)."],
        'page1_suptitle' : "Accueil - Easy PDF",
        'page1_welcome' : "Bienvenue !",
        'page1_instruction' : "Veuillez choisir ci-dessous la tâche que vous souhaitez accomplir.",
        'page1_merge_button' : "Fusionner des fichiers PDF",
        'page1_split_button' : "Extraire des pages d'un fichier PDF",
        'page2_suptitle' : "Fusion - Easy PDF",
        'page2_title' : "Fusionner des fichiers PDF",
        'page2_merge_button' : "Fusionner",
        'page2_clear_button' : "Tout supprimer",
        'page3_suptitle' : "Extraction - Easy PDF",
        'page3_title' : "Extraire des pages d'un fichier PDF",
        'page3_start_page' : "Page de début",
        'page3_stop_page' : "Page de fin",
        'page3_split_button' : "Extraire",
        'page3_size_yesno_title' : "PDF volumineux",
        'page3_size_yesno_message' : "La taille du PDF est supérieure à 200 Mo.\nVoulez-vous malgré tout l'afficher ?",
        'page3_zoom_label' : "Zoom",
        'page3_change_page_label' : "Page",
    },
    
    'English' : {
        'language' : ['French', 'English', 'German'],
        'self_language' : "English",
        'language_indication' : 'Choose a language',
        'quit' : "Close",
        'open_file' : "Load a new file",
        'select_file' : "Select a file",
        'save_file' : "Save a file",
        'go_back' : "Back to menu",
        'merge_complete_title' : "File saved",
        'merge_complete_message' : "The new PDF has been successfully saved!",
        'split_complete_title' : "File saved",
        'split_complete_message' : "The new PDF has been successfully saved!",
        'missing_start_page_title' : "Incorrect start page",
        'missing_start_page_message' : "Please indicate the page number from where you want to start extracting pages out of the PDF.\nIt should be a positive integer (no floating point).",
        'missing_stop_page_title' : "Incorrect stop page",
        'missing_stop_page_message' : "Please indicate the page number for which you want to stop extracting pages out of the PDF.\nIt should be a positive integer and it should be greater than the number given for the first page.",
        'start_stop_too_big_title' : "The PDF has less pages than you think ;)",
        'start_stop_too_big_message' : ["The numbers you provided for the first and/or last pages do not match the file size.\nPlease be aware that the file only has ", " page(s)."],
        'page1_suptitle' : "Home - Easy PDF",
        'page1_welcome' : "Welcome!",
        'page1_instruction' : "Please choose below the task that you want to perform.",
        'page1_merge_button' : "Merge PDF files",
        'page1_split_button' : "Extract pages from a PDF file",
        'page2_suptitle' : "Merge - Easy PDF",
        'page2_title' : "Merge PDF files",
        'page2_merge_button' : "Merge",
        'page2_clear_button' : "Clear all",
        'page3_suptitle' : "Extract - Easy PDF",
        'page3_title' : "Extract pages from a PDF file",
        'page3_start_page' : "First page",
        'page3_stop_page' : "Last page",
        'page3_split_button' : "Extract",
        'page3_size_yesno_title' : "Large PDF",
        'page3_size_yesno_message' : "The PDF size is greater than 200 Mo.\nDo you want to display it anyway?",
        'page3_zoom_label' : "Zoom",
        'page3_change_page_label' : "Page",
    },
    
    'German' : {
        'language' : ['Französisch', 'Englisch', 'Deutsch'],
        'self_language' : "Deutsch",
        'language_indication' : 'Wählen Sie eine Sprache',
        'quit' : "Verlassen",
        'open_file' : "Neue Datei laden",
        'select_file' : "Datei auswählen",
        'save_file' : "Datei speichern",
        'go_back' : "Zurück zum Menu",
        'merge_complete_title' : "Erfolgreiche Speicherung",
        'merge_complete_message' : "Die neue Datei wurde erfolgreich gespeichert !",
        'split_complete_title' : "Erfolgreiche Speicherung",
        'split_complete_message' : "Die neue Datei wurde erfolgreich gespeichert !",
        'missing_start_page_title' : "Erste Seite nicht korrekt",
        'missing_start_page_message' : "Bitte geben Sie die Nummer der Seite an, ab der Sie beginnen wollen, die Seiten aus der Datei zu extrahieren.\nDie eingegebene Zahl muss eine ganze Zahl (kein Vigilum) und positiv sein.",
        'missing_stop_page_title' : "Letzte Seite nicht korrekt",
        'missing_stop_page_message' : "Bitte geben Sie die Nummer der Seite an, bei der Sie aufhören wollen, die Seiten aus der Datei zu extrahieren\nDie eingegebene Zahl muss eine ganze Zahl (kein Vigilum), positiv, und größer als die für die erste Seite eingegebene Zahl sein.",
        'start_stop_too_big_title' : "Das PDF hat weniger Seiten, als Sie denken ;)",
        'start_stop_too_big_message' : ["Die Zahlen, die Sie für die erste und/oder letzte Seite eingegeben haben, stimmen nicht mit der Dateigröße überein.\nBitte beachten Sie, dass die Datei nur ", " Seite(n) hat."],
        'page1_suptitle' : "Home - Easy PDF",
        'page1_welcome' : 'Willkommen!',
        'page1_instruction' : "Bitte wählen Sie unten die Aufgabe aus, die Sie durchführen möchten.",
        'page1_merge_button' : "PDF Dateien zusammenführen",
        'page1_split_button' : "Seiten aus einer PDF Datei extrahieren",
        'page2_suptitle' : "Zusammenführung - Easy PDF",
        'page2_title' : "PDF Dataien zusammenführen",
        'page2_merge_button' : "Zusammenführen",
        'page2_clear_button' : "Alles löschen",
        'page3_suptitle' : "Extrahierung - Easy PDF",
        'page3_title' : "Seiten aus einer PDF Datei extrahieren",
        'page3_start_page' : "Erste Seite",
        'page3_stop_page' : "Letzte Seite",
        'page3_split_button' : "Extrahieren",
        'page3_size_yesno_title' : "Große PDF Datei",
        'page3_size_yesno_message' : "Die Größe der PDF-Datei ist größer als 200 MB.\nMöchten Sie die Datei trotzdem anzeigen?",
        'page3_zoom_label' : "Zoom",
        'page3_change_page_label' : "Seite",
    }
}

language_conversion = {
    'Français' : 'French',
    'French' : 'French',
    'Französisch' : 'French',
    'Anglais' : 'English',
    'English' : 'English',
    'Englisch' : 'English',
    'Allemand' : 'German',
    'German' : 'German',
    'Deutsch' : 'German',
}